./BNGMM -m example/3_prot_linear_sim/model.bngl -x example/3_prot_linear_sim/X -y example/3_prot_linear_sim/Y -t example/3_prot_linear_sim/time_steps.csv -r example/3_prot_linear_sim/true_rates.csv -c example/3_prot_linear_sim/Config.csv
./BNGMM -m example/6_pro_nonlin_sim_slim/6pro.bngl -c example/6_pro_nonlin_sim_slim/Config.csv -x example/6_pro_nonlin_sim_slim/X/ -y example/6_pro_nonlin_sim_slim/Y/ -t example/6_pro_nonlin_sim_slim/time_steps.csv -r example/6_pro_nonlin_sim_slim/true_rates.csv -o frontend/output/ --g
./BNGMM -m example/l3p_100_sim/model.bngl -x example/l3p_100_sim/X -y example/l3p_100_sim/Y -t example/l3p_100_sim/time_steps.csv -r example/l3p_100_sim/true_rates.csv -c example/l3p_100_sim/Config.csv
./BNGMM -m example/3_prot_linear_sim/model.bngl -x example/3_prot_linear_sim/X -y example/3_prot_linear_sim/Y -t example/3_prot_linear_sim/time_steps.csv -r example/3_prot_linear_sim/true_rates.csv -c example/3_prot_linear_sim/Config.csv -hr example/3_prot_linear_sim/heldRates.csv
./BNGMM -m example/3_prot_linear_sim/model.bngl -x example/3_prot_linear_sim/X -y example/3_prot_linear_sim/Y -t example/3_prot_linear_sim/time_steps.csv -r example/3_prot_linear_sim/true_rates.csv -c example/3_prot_linear_sim/Config.csv -s example/3_prot_linear_sim/true_rates.csv
./BNGMM -m example/l3p_100_sim/model.bngl -x example/l3p_100_sim/X -y example/l3p_100_sim/Y -t example/l3p_100_sim/time_steps.csv -r example/l3p_100_sim/true_rates.csv -c example/l3p_100_sim/Config.csv -s example/3_prot_linear_sim/true_rates.csv
./BNGMM -m example/3_prot_linear_sim/model.bngl -x example/3_prot_linear_sim/X -y example/3_prot_linear_sim/Y -t example/3_prot_linear_sim/time_steps.csv -r example/3_prot_linear_sim/true_rates.csv -c example/3_prot_linear_sim/Config.csv -f example/3_prot_linear_sim/future_times.csv --contour -o test/ 
./BNGMM -m example/4_prot_CD3_CD8_CD28/4proV2.bngl -c example/4_prot_CD3_CD8_CD28/Config4pro.csv -x example/4_prot_CD3_CD8_CD28/1min_2min/X/ -y example/4_prot_CD3_CD8_CD28/1min_2min/Y/ -t example/4_prot_CD3_CD8_CD28/time_steps.csv -o test/ -f example/yeast/future_times.csv
./BNGMM -m example/yeast/yeast.bngl -x example/yeast/X -y example/yeast/Y -t example/yeast/time_steps.csv -r example/yeast/true_rates.csv -c example/yeast/Config.csv -hr example/yeast/heldRates.csv -f example/yeast/future_times.csv -o test/ --g



./BNGMM -m example/6_pro_lin_sim/6_pro_lin.bngl -c example/6_pro_lin_sim/Config.csv -x example/6_pro_lin_sim/X -y example/6_pro_lin_sim/Y -t example/6_pro_lin_sim/ts.csv -r example/6_pro_lin_sim/tr.csv -o test/ --g